"""model game

Revision ID: b818cd8cd038
Revises: 9716eb7ec195
Create Date: 2024-09-30 18:41:04.757567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b818cd8cd038'
down_revision: Union[str, None] = '9716eb7ec195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('rules', sa.String(), nullable=False))
    op.add_column('games', sa.Column('min_people', sa.Integer(), nullable=False))
    op.add_column('games', sa.Column('max_people', sa.Integer(), nullable=False))
    op.add_column('games', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.drop_column('games', 'rule_description')
    op.drop_column('games', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('games', sa.Column('rule_description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('games', 'is_active')
    op.drop_column('games', 'max_people')
    op.drop_column('games', 'min_people')
    op.drop_column('games', 'rules')
    # ### end Alembic commands ###
