"""model gameroom add

Revision ID: 46fd0fdc630c
Revises: ee7a2a3bc4c2
Create Date: 2024-10-24 21:29:05.800902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46fd0fdc630c'
down_revision: Union[str, None] = 'ee7a2a3bc4c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_game_room_game_id_games')),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], name=op.f('fk_game_room_office_id_offices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_room'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_room')
    # ### end Alembic commands ###
