services:
  reverse-proxy:
    image: traefik:v3.1
    container_name: traefik
    ports:
      - 80:80
      - 443:443
    restart: always
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=web"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=gayfullin.r.i@yandex.ru"
    labels:
      - "traefik.enable=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt/:/letsencrypt/
      - ./traefik_config/:/etc/traefik

  backend:
    build:
      dockerfile: ./Dockerfile.back
    container_name: backend
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: always
    command: /bin/sh run.sh
    volumes:
      - ./media:/app/media
      - ./app:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`${API_DOMAIN_NAME}`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.backend-service.loadbalancer.server.port=8000"

  frontend:
    image: nginx:alpine
    container_name: frontend
    restart: always
    volumes:
      - ./nginx/nginx_default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/var/www/html:ro
      - media:/var/www/media:ro
    labels:
      - "traefik.http.routers.frontend.rule=Host(`${DOMAIN_NAME}`) || Host(`${API_DOMAIN_NAME}`) && PathPrefix(`/media/`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.frontend.loadbalancer.server.port=81"

  db:
    image: postgres:alpine
    container_name: postgresql
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 3s
    volumes:
      - data:/var/lib/postgresql/data/

  redis:
    image: redis:alpine
    container_name: redis

volumes:
  data:
  media:
