services:
  reverse-proxy:
    image: traefik:v3.1
    container_name: traefik
    ports:
      - 80:80
      - 443:443
    command:
      # - --log.level=DEBUG
      - --providers.docker
      - --providers.docker.exposedbydefault=false

    labels:
      - "traefik.enable=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # - ./.cert/:/cert
      # - ./traefik_config/:/etc/traefik

  frontend:
    build:
      dockerfile: ./Dockerfile.frontend
    container_name: frontend
    depends_on:
      - backend
    env_file:
      - .env
    restart: always
    volumes:
      - ./dist:/dist
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`gsd-games.ru`)"
      # - "traefik.http.routers.frontend.tls=true"
      # - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.services.frontend-service.loadbalancer.server.port=3000"
    command: serve -s /dist

  backend:
    build:
      dockerfile: ./Dockerfile.back.prod
      # args:
      #   - USERNAME=${DOCKER_USER}
      #   - USER_ID=${USER_ID}
    container_name: backend
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: always
    command: /bin/sh run.sh
    volumes:
      - ./media:/app/media
      - ./app:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.gsd-games.ru`)"
      # - "traefik.http.routers.backend.tls=true"
      # - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.services.backend-service.loadbalancer.server.port=8000"

  db:
    image: postgres:alpine
    container_name: postgresql
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 3s
    volumes:
      - data:/var/lib/postgresql/data/

  redis:
    image: redis:alpine
    container_name: redis

  celery:
    build:
      dockerfile: ./Dockerfile.back.prod
    depends_on:
    restart: always
    volumes:
      - ./apps:/app
    command: celery -A celery_app worker -l INFO
    env_file:
      - .env

volumes:
  media:
  data:
