# syntax=docker/dockerfile:1
FROM python:3.12-alpine

# ARG USERNAME
# ARG USER_ID
# ARG GROUP_ID=$USER_ID

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONBUFFERED=1 \ 
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100

COPY pyproject.toml poetry.lock ./

# RUN addgroup -S --gid $GROUP_ID $USERNAME \
#     && adduser -S --uid $USER_ID -G $USERNAME $USERNAME  --disabled-password \
#     && pip install poetry && \
#     poetry config virtualenvs.create false && \
#     poetry install --only main --no-interaction

RUN pip install poetry && \
    poetry config virtualenvs.create false && \
    poetry install --only main --no-interaction

EXPOSE 8000

WORKDIR /app

# USER $USERNAME