"""games image

Revision ID: 9716eb7ec195
Revises: 6092bf7d2c18
Create Date: 2024-08-07 20:49:08.309474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9716eb7ec195'
down_revision: Union[str, None] = '6092bf7d2c18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('image', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'image')
    # ### end Alembic commands ###
