server {
  listen 81;
  listen [::]:81;
  client_max_body_size 10M;
  
  location /media {
    alias /var/www/media;
  }

  location / {
    root /var/www/html;
    index index.html index.htm;
    try_files $uri $uri/ /index.html =404;
  }
}
