entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

tls:
  certificates:
    - certFile: /cert/gsd_game.ru.crt
      keyFile: /cert/gsd_game.ru.key

providers:
  docker:
    network: traefik-network
